* The Game of the Amazons

A web app providing a simple venue for playing the [[https://en.wikipedia.org/wiki/Game_of_the_Amazons][Game of the Amazons]] online
with other others.

In early stages of development, and not yet hosted anywhere.

* Instructions

This project was (initially) generated by eliom-distillery as the basic
project "amazons", and is largely an exercise 

Generally, you can compile it and run ocsigenserver on it by
  $ make test.byte (or test.opt)

** Makefile targets

 Here's some help on how to work with this basic distillery project:

  - Test the application by compiling it and running ocsigenserver locally
      $ make test.byte (or test.opt)

  - Compile it only
      $ make all (or byte or opt)

  - Deploy the project on your system
      $ sudo make install (or install.byte or install.opt)

  - Run the server on the deployed project
      $ sudo make run.byte (or run.opt)

    If WWWUSER in the Makefile.options is you, you don't need the
    `sudo'. If Eliom isn't installed globally, however, you need to
    re-export some environment variables to make this work:
      $ sudo PATH=$PATH OCAMLPATH=$OCAMLPATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH make run.byte/run.opt

  - If you need a findlib package in your project, add it to the
    variables SERVER_PACKAGES and/or CLIENT_PACKAGES. The configuration
    file will be automatically updated.
