* The Game of the Amazons

A web app providing a simple venue for playing the [[https://en.wikipedia.org/wiki/Game_of_the_Amazons][Game of the Amazons]] online
with other others.

** Current status

   In very early stages of development, and not yet hosted anywhere.

   The game logic is mostly complete.
   The server side only has a rough start.
   The client side isn't started.

   This project started as a way of learning the Ocsigen's [[http://ocsigen.org/eliom/][Eliom]] framework. I ended
   up learning enough to realize that the framework has too much magic and too few
   safeguards against shooting yourself in the foot for it to be a usable tool
   given my current level of (in)expertise and my current aims.

   I'm migrating the working parts of the server-side of the project to the much
   more lightweight [[https://github.com/rgrinberg/opium][opium]] library. The game logic has been split in to its own
   library, and the client side will take shape in its own package as well.

** Development

*** OCaml Dependencies

    - jbuilder
    - core
    - ppx_deriving
    - ppx_deriving_yojson
    - opium
    - tyxml

*** Build and install the game library:
    #+BEGIN_SRC sh
      $ cd lib
      $ jbuilder build @insetall && jbduiler install
    #+END_SRC

*** Build and run the server:
    #+BEGIN_SRC sh
      $ cd srv
      $ jbuilder build && _build/default/lib/srv.exe
    #+END_SRC

    Then visit localhost:3000.
