* The Game of the Amazons

A web app providing a simple venue for playing the [[https://en.wikipedia.org/wiki/Game_of_the_Amazons][Game of the Amazons]] online
with other others.

In early stages of development, and not yet hosted anywhere.

* Instructions

This project was (initially) generated by eliom-distillery as the basic
project "amazons", and is largely an exercise in learning Ocsigen and Eliom.

Generally, you can compile it and run ocsigenserver on it by

#+BEGIN_SRC sh
$ make test.byte (or test.opt)
#+END_SRC

** Makefile targets

   Here's some help on how to work with this basic distillery project:

   - Test the application by compiling it and running ocsigenserver locally

     #+BEGIN_SRC sh
     $ make test.byte (or test.opt)
     #+END_SRC

   - Compile it only

     #+BEGIN_SRC sh
     $ make all (or byte or opt)
     #+END_SRC

   - Deploy the project on your system

     #+BEGIN_SRC sh
     $ sudo make install (or install.byte or install.opt)
     #+END_SRC

   - Run the server on the deployed project

     #+BEGIN_SRC sh
     $ sudo make run.byte (or run.opt)
     #+END_SRC

     If WWWUSER in the Makefile.options is you, you don't need the
     `sudo'. If Eliom isn't installed globally, however, you need to
     re-export some environment variables to make this work:

     #+BEGIN_SRC sh
     $ sudo PATH=$PATH OCAMLPATH=$OCAMLPATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH make run.byte/run.opt
     #+END_SRC

   - If you need a findlib package in your project, add it to the
     variables SERVER_PACKAGES and/or CLIENT_PACKAGES. The configuration
     file will be automatically updated.
