lib: [
  "_build/install/default/lib/game/META" {"META"}
  "_build/install/default/lib/game/opam" {"opam"}
  "_build/install/default/lib/game/game.cmi"
  "_build/install/default/lib/game/game.cmx"
  "_build/install/default/lib/game/game.cmt"
  "_build/install/default/lib/game/game.ml"
  "_build/install/default/lib/game/game.cma"
  "_build/install/default/lib/game/game.cmxa"
  "_build/install/default/lib/game/game.a"
  "_build/install/default/lib/game/game.cmxs"
]
bin: [
  "_build/install/default/bin/test_game" {"test_game"}
]
